from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ScaffoldFile:
    path: str
    content: str


@dataclass(frozen=True)
class ScaffoldDir:
    path: str


def placeholder_md(title: str) -> str:
    return f"""# {title}

> Placeholder gerado por tech-agentes. Ajuste conforme o projeto.
"""

def placeholder_json() -> str:
    return "{}\n"


def base_scaffold() -> tuple[list[ScaffoldDir], list[ScaffoldFile]]:
    dirs = [
        ScaffoldDir("docs/brief"),
        ScaffoldDir("docs/padrões"),
        ScaffoldDir("docs/seguranca"),
        ScaffoldDir("docs/modelos"),
        ScaffoldDir("docs/decisoes/adr"),
        ScaffoldDir("docs/dados"),
        ScaffoldDir("agents/specialists"),
        ScaffoldDir("prompts"),
        ScaffoldDir("workflows"),
        ScaffoldDir("integrations"),
        ScaffoldDir("dashboards"),
        ScaffoldDir("evals/resultados"),
        ScaffoldDir("observability"),
        ScaffoldDir("observability/providers"),
        ScaffoldDir("devops/infra"),
        ScaffoldDir("logs"),
        ScaffoldDir("configs"),
        ScaffoldDir("templates"),
        ScaffoldDir("outputs/artefatos_gerados"),
    ]

    files = [
        ScaffoldFile("docs/brief/brief_atual.md", placeholder_md("Brief Atual")),
        ScaffoldFile("docs/padrões/padroes_projeto.md", placeholder_md("Padrões do Projeto")),
        ScaffoldFile("docs/seguranca/politicas.md", placeholder_md("Políticas de Segurança")),
        ScaffoldFile("docs/modelos/guia_modelos.md", placeholder_md("Guia de Modelos")),
        ScaffoldFile(
            "docs/decisoes/adr/ADR-YYYYMMDD-template.md",
            placeholder_md("ADR Template"),
        ),
        ScaffoldFile("docs/dados/data_contracts.md", placeholder_md("Data Contracts")),
        ScaffoldFile("agents/contexto_requisitos.md", placeholder_md("Agente: Contexto & Requisitos")),
        ScaffoldFile("agents/orquestrador.md", placeholder_md("Agente: Orquestrador")),
        ScaffoldFile("agents/engenharia_prompt.md", placeholder_md("Agente: Engenharia de Prompt")),
        ScaffoldFile("agents/seguranca_compliance.md", placeholder_md("Agente: Segurança & Compliance")),
        ScaffoldFile("agents/observabilidade_custos.md", placeholder_md("Agente: Observabilidade & Custos")),
        ScaffoldFile(
            "agents/eng_software_arquiteto_ia_devops.md",
            placeholder_md("Agente: Eng. Software / Arquiteto IA & DevOps"),
        ),
        ScaffoldFile(
            "agents/qualidade_auditoria_testes.md",
            placeholder_md("Agente: Qualidade, Auditoria & Testes"),
        ),
        ScaffoldFile("prompts/templates_analise.md", placeholder_md("Templates: Análise")),
        ScaffoldFile("prompts/templates_extracao.md", placeholder_md("Templates: Extração")),
        ScaffoldFile("prompts/templates_geracao.md", placeholder_md("Templates: Geração")),
        ScaffoldFile("prompts/templates_decisao.md", placeholder_md("Templates: Decisão")),
        ScaffoldFile("workflows/plano_execucao.json", placeholder_json()),
        ScaffoldFile("workflows/backlog_tarefas.json", placeholder_json()),
        ScaffoldFile("integrations/inventario_sistemas.json", placeholder_json()),
        ScaffoldFile("integrations/specs_endpoints.md", placeholder_md("Specs de Endpoints")),
        ScaffoldFile("integrations/mapeamentos_schemas.json", placeholder_json()),
        ScaffoldFile("dashboards/requisitos_kpis.md", placeholder_md("Requisitos de KPIs")),
        ScaffoldFile("evals/golden_sets.json", placeholder_json()),
        ScaffoldFile("evals/rubricas.json", placeholder_json()),
        ScaffoldFile("observability/dashboards.json", placeholder_json()),
        ScaffoldFile("observability/relatorios_periodicos.md", placeholder_md("Relatórios Periódicos")),
        ScaffoldFile("devops/pipelines.yaml", "# pipelines\n"),
        ScaffoldFile("devops/runbooks.md", placeholder_md("Runbooks")),
        ScaffoldFile("logs/.gitkeep", ""),  # keep folder
        ScaffoldFile("logs/costs.summary.json", "{}\n"),
        ScaffoldFile("configs/projeto.json", placeholder_json()),
        ScaffoldFile("configs/modelos.json", placeholder_json()),
        ScaffoldFile("configs/ambientes.json", placeholder_json()),
    ]

    # Templates kit (subset now; full kit generated by bootstrap script)
    files.append(ScaffoldFile("templates/README.md", placeholder_md("Templates README")))

    return dirs, files

